# Generated by Django 2.2.5 on 2019-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190919_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_hora',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='titular',
            field=models.CharField(max_length=120),
        ),
    ]
